// Shared category constants to ensure consistency across the application
export const BOOK_CATEGORIES = [
  'Fiction', 
  'Non-Fiction', 
  'Mystery', 
  'Romance', 
  'Sci-Fi', 
  'Fantasy',
  'Biography', 
  'History', 
  'Self-Help', 
  'Technology', 
  'Business', 
  'Health',
  'Travel', 
  'Cooking', 
  'Art', 
  'Education', 
  'Children', 
  'Poetry', 
  'Drama', 
  'Science', 
  'Mythology', 
  'Other'
];