import React, { useState } from 'react';
import { useQuery } from 'react-query';
import { useSearchParams } from 'react-router-dom';
import api from '../utils/api';
import BookCard from '../components/books/BookCard';
import CategoryContent from '../components/books/CategoryContent';
import LoadingSpinner from '../components/ui/LoadingSpinner';
import SEOHead from '../components/ui/SEOHead';
import Breadcrumbs from '../components/ui/Breadcrumbs';
import { Squares2X2Icon, ListBulletIcon } from '@heroicons/react/24/outline';
import { BOOK_CATEGORIES } from '../constants/categories';
import { getCategoryInfo } from '../constants/categoryDescriptions';
import { 
  generateSEOMetadata, 
  generateBookCollectionStructuredData
} from '../utils/seoUtils';

const BooksPage = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const [filters, setFilters] = useState({
    page: 1,
    limit: 12,
    category: searchParams.get('category') || '',
    search: searchParams.get('search') || '',
    sortBy: searchParams.get('sortBy') || 'createdAt',
    sortOrder: searchParams.get('sortOrder') || 'desc',
    minPrice: searchParams.get('minPrice') || '',
    maxPrice: searchParams.get('maxPrice') || '',
    featured: searchParams.get('featured') || '',
    bestseller: searchParams.get('bestseller') || '',
    newArrival: searchParams.get('newArrival') || ''
  });
  const [viewMode, setViewMode] = useState('grid');

  // Fetch books
  const { data, isLoading, error } = useQuery(
    ['books', filters],
    () => {
      const params = new URLSearchParams();
      Object.entries(filters).forEach(([key, value]) => {
        if (value) params.append(key, value);
      });
      return api.get(`/api/books?${params}`).then(res => res.data);
    },
    { keepPreviousData: true }
  );

  // Fetch categories with fallback
  const { data: apiCategories } = useQuery(
    'categories',
    () => api.get('/api/categories').then(res => res.data),
    {
      staleTime: 5 * 60 * 1000,
      retry: 2,
      onError: () => {
        // Silently fail, we'll use fallback
      }
    }
  );

  // Use API categories if available, otherwise fall back to static categories
  const categories = React.useMemo(() => {
    if (apiCategories && Array.isArray(apiCategories) && apiCategories.length > 0) {
      return apiCategories;
    }
    // Fallback to static categories
    return BOOK_CATEGORIES.map(name => ({ _id: name, name }));
  }, [apiCategories]);

  const updateFilters = (newFilters) => {
    const updatedFilters = { ...filters, ...newFilters, page: 1 };
    setFilters(updatedFilters);
    
    // Update URL params
    const params = new URLSearchParams();
    Object.entries(updatedFilters).forEach(([key, value]) => {
      if (value && key !== 'page' && key !== 'limit') {
        params.set(key, value);
      }
    });
    setSearchParams(params);
  };

  const handlePageChange = (page) => {
    setFilters(prev => ({ ...prev, page }));
  };

  // Generate SEO metadata based on current filters
  const seoData = generateSEOMetadata({
    filters,
    totalResults: data?.pagination?.total || 0
  });

  // Enhanced SEO for category pages
  const categoryInfo = filters.category ? getCategoryInfo(filters.category) : null;
  const enhancedSeoData = categoryInfo ? {
    title: `${categoryInfo.title} - Buy Online at BoiBabu.in`,
    description: categoryInfo.description + ` Browse ${data?.pagination?.total || 0} books with best prices and free shipping.`,
    keywords: categoryInfo.keywords + ', BoiBabu, buy books online, free shipping'
  } : seoData;

  // Generate breadcrumbs
  const breadcrumbs = [];
  if (filters.category) {
    breadcrumbs.push({ label: 'Books', href: '/books' });
    breadcrumbs.push({ label: filters.category, href: `/books?category=${encodeURIComponent(filters.category)}` });
  } else if (filters.search) {
    breadcrumbs.push({ label: 'Books', href: '/books' });
    breadcrumbs.push({ label: `Search: ${filters.search}` });
  } else {
    breadcrumbs.push({ label: 'All Books' });
  }

  // Generate structured data
  const structuredData = generateBookCollectionStructuredData({
    title: enhancedSeoData.title,
    description: enhancedSeoData.description,
    url: `https://boibabu.in/books`, // Will be properly generated by SEOHead
    books: data?.books || [],
    totalResults: data?.pagination?.total || 0
  });

  return (
    <>
      <SEOHead
        title={enhancedSeoData.title}
        description={enhancedSeoData.description}
        keywords={enhancedSeoData.keywords}
        searchParams={searchParams}
        basePath="/books"
        structuredData={structuredData}
        type="website"
      />

      <div className="min-h-screen bg-gray-50 py-8">
      <div className="container mx-auto px-4">
        {/* Breadcrumbs */}
        <Breadcrumbs items={breadcrumbs} />
        
        {/* Category Content - Only show for category pages */}
        {filters.category && (
          <CategoryContent 
            categoryName={filters.category} 
            bookCount={data?.pagination?.total || 0}
          />
        )}
        
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-4">
            {filters.category ? `${filters.category} Books` : 
             filters.search ? `Search Results for "${filters.search}"` : 
             'All Books'}
          </h1>
          
          {/* Filters Bar */}
          <div className="bg-white rounded-lg shadow-sm p-6 mb-6">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              {/* Category Filter */}
              <select
                value={filters.category}
                onChange={(e) => updateFilters({ category: e.target.value })}
                className="form-input"
              >
                <option value="">All Categories</option>
                {categories?.map(category => (
                  <option key={category._id} value={category.name}>{category.name}</option>
                ))}
              </select>

              {/* Sort By */}
              <select
                value={`${filters.sortBy}-${filters.sortOrder}`}
                onChange={(e) => {
                  const [sortBy, sortOrder] = e.target.value.split('-');
                  updateFilters({ sortBy, sortOrder });
                }}
                className="form-input"
              >
                <option value="createdAt-desc">Newest First</option>
                <option value="createdAt-asc">Oldest First</option>
                <option value="price-asc">Price: Low to High</option>
                <option value="price-desc">Price: High to Low</option>
                <option value="title-asc">Title: A to Z</option>
                <option value="title-desc">Title: Z to A</option>
              </select>

              {/* Price Range */}
              <div className="flex gap-2">
                <input
                  type="number"
                  placeholder="Min Price"
                  value={filters.minPrice}
                  onChange={(e) => updateFilters({ minPrice: e.target.value })}
                  className="form-input"
                />
                <input
                  type="number"
                  placeholder="Max Price"
                  value={filters.maxPrice}
                  onChange={(e) => updateFilters({ maxPrice: e.target.value })}
                  className="form-input"
                />
              </div>

              {/* Special Filters */}
              <div className="flex gap-2">
                <label className="flex items-center">
                  <input
                    type="checkbox"
                    checked={filters.featured === 'true'}
                    onChange={(e) => updateFilters({ featured: e.target.checked ? 'true' : '' })}
                    className="mr-2"
                  />
                  Featured
                </label>
                <label className="flex items-center">
                  <input
                    type="checkbox"
                    checked={filters.bestseller === 'true'}
                    onChange={(e) => updateFilters({ bestseller: e.target.checked ? 'true' : '' })}
                    className="mr-2"
                  />
                  Bestseller
                </label>
              </div>
            </div>
          </div>

          {/* Results Header */}
          <div className="flex justify-between items-center">
            <p className="text-gray-600">
              {data ? `Showing ${data.books?.length || 0} of ${data.pagination?.total || 0} books` : ''}
            </p>
            
            <div className="flex items-center gap-2">
              <button
                onClick={() => setViewMode('grid')}
                className={`p-2 rounded ${viewMode === 'grid' ? 'bg-primary-600 text-white' : 'bg-gray-200'}`}
              >
                <Squares2X2Icon className="h-5 w-5" />
              </button>
              <button
                onClick={() => setViewMode('list')}
                className={`p-2 rounded ${viewMode === 'list' ? 'bg-primary-600 text-white' : 'bg-gray-200'}`}
              >
                <ListBulletIcon className="h-5 w-5" />
              </button>
            </div>
          </div>
        </div>

        {/* Books Grid */}
        {isLoading ? (
          <LoadingSpinner size="lg" className="py-20" />
        ) : error ? (
          <div className="text-center py-20">
            <p className="text-red-600">Error loading books. Please try again.</p>
          </div>
        ) : data?.books?.length === 0 ? (
          <div className="text-center py-20">
            <p className="text-gray-600">No books found matching your criteria.</p>
          </div>
        ) : (
          <>
            <div className={`grid gap-6 ${
              viewMode === 'grid' 
                ? 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4' 
                : 'grid-cols-1'
            }`}>
              {data?.books?.map((book) => (
                <BookCard key={book._id} book={book} />
              ))}
            </div>

            {/* Pagination */}
            {data?.pagination?.pages > 1 && (
              <div className="flex justify-center mt-12">
                <div className="flex gap-2">
                  {Array.from({ length: data.pagination.pages }, (_, i) => i + 1).map(page => (
                    <button
                      key={page}
                      onClick={() => handlePageChange(page)}
                      className={`px-4 py-2 rounded ${
                        page === filters.page
                          ? 'bg-primary-600 text-white'
                          : 'bg-white text-gray-700 hover:bg-gray-50'
                      }`}
                    >
                      {page}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
    </>
  );
};

export default BooksPage;